name: Deploy
on:
  push:
    branches: master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build client
        working-directory: "solid/"
        run: "bun install && bun run build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "skarmdelarne"
          entrypoint: "src/dd.ts"
          root: "."
